### ISSUE TITLE
Logo for GoSport

### ISSUE THREAD

**Issue by Yasujizr** [MartinKamenov/GoSport#8]
I ran into your project while you were walking around Github. I design a logo for open source projects to do things I can put in sites like Dribbble, Behance. I can design a Logo for you if you want. What kind of Logo do you want? What are the benefits of the program? What are your favorite logo samples?

If you say these, I can design a logo for you.

**Comment by MartinKamenov** [comment]
Hello @Yasujizr,
I would like to know more about what you offer, so if you have LinkedIn profile I would like to have a talk with you. You can find me here https://www.linkedin.com/in/martin-kamenov-59b03a144/
